version: '3'

services:
    redis:
        container_name: redis
        image: 'redis:alpine'
        restart: always
        ports:
            - '6379:6379'
        networks:
            - app

    postgres:
        container_name: postgres
        image: postgres:9.6
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: 123456
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./scripts/database:/database
        networks:
            - app

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management-alpine
        restart: always
        ports:
            - '15672:15672'
            - '5672:5672'
        networks:
            - app

    influxdb:
        image: influxdb
        restart: always
        ports:
            - '8086:8086'
        environment:
            INFLUXDB_DB: rant
        volumes:
            - influx-db-data:/var/lib/influxdb     
        networks:
            - app

networks:
    app:

volumes:
    mongo-db-data:
    influx-db-data:
    db-data:
